apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-v1
spec:
  template:
    spec:
      containers:
        - image: docker.io/diego727/ex-app:v1
          ports:
            - containerPort: 8080
